# Action 的名字
name: Python application

on:
  schedule:
    - cron: '30 12 * * *'
    - cron: '20/15 * * * *'
  # 触发条件2：手动按钮
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: get-today-github
      run: |
        ls -alh
        python run.py
    - name: git-pull-code
      run: |
        git config --global user.name "WHG555"
        git config --global user.email "whghcyx@outlook.com"
        git add .
        git commit -m "feat: Update code"
        git push https://${{secrets.TODAY_GITHUB_KEY}}@github.com/${{ github.repository }}.git HEAD:main
      env:
        GH_TOKEN: ${{ secrets.TODAY_GITHUB_KEY }}
