# Action 的名字
name: Python application

on:
  # 触发条件1：main 分支收到 push 后执行任务。
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # 触发条件2：手动按钮
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: get-today-github
      run: |
        ls -alh
        python run.py
    - name: git-pull-code
      run: |
        git config --global user.name "WHG555"
        git config --global user.email "whghcyx@outlook.com"
        git add .
        git commit -m "feat: Update code"
        git push https://github.com/${{ github.repository }}.git HEAD:main
      env:
        GH_TOKEN: ${{ secrets.TODAY_GITHUB_KEY }}
    - uses: actions/stale@v5
    - uses: rematocorp/open-pull-request-action@v1
      with:
        # Github token, https://docs.github.com/en/actions/reference/authentication-in-a-workflow
        github-token: ${{secrets.TODAY_GITHUB_KEY}}
        # head branch
        from-branch: main
        # base branch
        to-branch: main
        # 
        repository-owner: WHG555
        # 
        repository: github-today-repositories
